import { createInterface } from "node:readline/promises";
import { stdin, stdout } from "node:process";
import { randomBytes } from "node:crypto";
import { openStore, passwordHash } from "../server/store.js";
const rl = createInterface({ input: stdin, output: stdout });
try {
  const username =
    process.env.ADMIN_USERNAME ||
    (await rl.question("Admin username: ")).trim();
  // Password is generated by default so it is never echoed during terminal input.
  const password =
    process.env.ADMIN_PASSWORD || randomBytes(24).toString("base64url");
  if (!/^[A-Za-z0-9_.-]{3,64}$/.test(username))
    throw new Error(
      "Use 3–64 letters, numbers, dots, underscores or hyphens for the username.",
    );
  if (password.length < 14 || password.length > 256)
    throw new Error("Password must be 14–256 characters.");
  const db = openStore();
  try {
    if (
      db.prepare("SELECT 1 FROM admins WHERE username=?").get(username) &&
      process.env.RESET_ADMIN !== "yes"
    )
      throw new Error(
        "Admin already exists. Set RESET_ADMIN=yes to rotate its password and revoke sessions.",
      );
    const hash = await passwordHash(password);
    db.exec("BEGIN IMMEDIATE");
    try {
      db.prepare(
        "INSERT INTO admins (username,password_hash) VALUES (?,?) ON CONFLICT(username) DO UPDATE SET password_hash=excluded.password_hash",
      ).run(username, hash);
      db.prepare("DELETE FROM sessions WHERE username=?").run(username);
      db.exec("COMMIT");
    } catch (error) {
      db.exec("ROLLBACK");
      throw error;
    }
    console.log(`Admin created: ${username}`);
    if (!process.env.ADMIN_PASSWORD)
      console.log(`Generated password (save privately): ${password}`);
    console.log("Open /#admin to sign in.");
  } finally {
    db.close();
  }
} catch (error) {
  console.error(error.message);
  process.exitCode = 1;
} finally {
  rl.close();
}
